---
apiVersion : v1
kind : Service
metadata :
  name : djangoapps-svc
  namespace: application
spec :
  selector :
    app : djangoapps
  type : LoadBalancer
  ports :
    - port : 8000
      targetPort : 8000
---
apiVersion : apps/v1
kind : Deployment
metadata :
  name : djangoapps
  namespace: application
spec :
  replicas : 1
  selector :
    matchLabels :
      app : djangoapps
  template :
    metadata :
      labels :
        app : djangoapps
    spec :
      containers :
      - name : djangoapps
        image: docker.io/aleksander7/crud:v1.3
        ports :
          - containerPort : 8000
        imagePullPolicy : Always
