---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: devops-application
  name: devops-application
  namespace: prod
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: devops-application
  template:
    metadata:
      labels:
        app: devops-application
    spec:
      containers:
        - image: docker.io/aleksander7/djangoapp:v1
          imagePullPolicy: Always
          name: devops-application
          ports:
          - containerPort: 8000
            name: http
      terminationGracePeriodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  name: devops-application-svc
  namespace: prod
spec:
  ports:
    - name: http-web
      nodePort: 30080
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: devops-application
  type: LoadBalancer
